'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Crunchyroll_Downloader.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property about_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("about_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_mass_cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_mass_cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property add_mass_cancel_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_mass_cancel_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {&quot;sources&quot;:[{&quot;file&quot;:&quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property AoD_files() As String
            Get
                Return ResourceManager.GetString("AoD_files", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;h1 itemprop=&quot;name&quot;&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property AoD_HTML_Anime_Title() As String
            Get
                Return ResourceManager.GetString("AoD_HTML_Anime_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;h3 class=&quot;episodebox-title&quot; title=&quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property AoD_HTML_Episode_Title() As String
            Get
                Return ResourceManager.GetString("AoD_HTML_Episode_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot;image&quot;:&quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property AoD_Image() As String
            Get
                Return ResourceManager.GetString("AoD_Image", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot;mediaid&quot;: ähnelt.
        '''</summary>
        Friend ReadOnly Property AoD_MediaID() As String
            Get
                Return ResourceManager.GetString("AoD_MediaID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot;title&quot;:&quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property AoD_Titel() As String
            Get
                Return ResourceManager.GetString("AoD_Titel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die [Script Info]
        '''; Template for error handling in the Crunchyrol Downloader by hama3254 https://github.com/hama3254/Crunchyroll-Downloader-v3.0
        '''; ass file from https://github.com/Aegisub/Aegisub/blob/master/automation/v4-docs/template-scripting-ideas.ass 
        '''; Script generated by Aegisub v2.00 PRE-RELEASE (SVN r939, jfs)
        '''; http://www.aegisub.net
        '''Title: Default Aegisub file
        '''ScriptType: v4.00+
        '''WrapStyle: 0
        '''PlayResX: 640
        '''PlayResY: 480
        '''Video Aspect Ratio: 0
        '''Video Zoom: 6
        '''Video Position: 0
        '''
        '''[V4+ Styles]        ''' [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property ass_template() As String
            Get
                Return ResourceManager.GetString("ass_template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balken() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balken", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balken_console() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balken_console", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;img id=&quot;footer_country_flag&quot; src=&quot;https://www.crunchyroll.com/i/country_flags/ ähnelt.
        '''</summary>
        Friend ReadOnly Property CC_String() As String
            Get
                Return ResourceManager.GetString("CC_String", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die display_episode_number&quot;:&quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property CR_Episode_Nr() As String
            Get
                Return ResourceManager.GetString("CR_Episode_Nr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;meta property=&quot;og:url&quot; content=&quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property CR_Head_Url_Split() As String
            Get
                Return ResourceManager.GetString("CR_Head_Url_Split", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;h4 id=&quot;showmedia_about_name&quot; class=&quot;strong&quot;&gt;“ ähnelt.
        '''</summary>
        Friend ReadOnly Property CR_MediaName() As String
            Get
                Return ResourceManager.GetString("CR_MediaName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ”&lt;/h4&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property CR_MediaName2() As String
            Get
                Return ResourceManager.GetString("CR_MediaName2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;/span&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property CR_MovieBT() As String
            Get
                Return ResourceManager.GetString("CR_MovieBT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;span itemprop=&quot;name&quot;&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property CR_MovieTop() As String
            Get
                Return ResourceManager.GetString("CR_MovieTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die seasonNumber&quot;:&quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property CR_Season_Nr() As String
            Get
                Return ResourceManager.GetString("CR_Season_Nr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crdSettings_Button_SafeExit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crdSettings_Button_SafeExit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crdSettings_Button_SafeExit_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crdSettings_Button_SafeExit_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DialogNotFound_Submit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DialogNotFound_Submit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DialogNotFound_Submit_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DialogNotFound_Submit_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download_subs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download_subs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download_subs_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download_subs_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE HTML PUBLIC &quot;-//IETF//DTD HTML 2.0//EN&quot;&gt;
        '''&lt;html&gt;&lt;head&gt;
        '''&lt;title&gt;404 Not Found&lt;/title&gt;
        '''&lt;/head&gt;&lt;body&gt;
        '''&lt;h1&gt;Not Found&lt;/h1&gt;
        '''&lt;p&gt;The requested URL was not found on this server.&lt;/p&gt;
        '''&lt;hr&gt;
        '''&lt;address&gt;Server at Crunchyroll Downloader Port 8080&lt;/address&gt;
        '''&lt;/body&gt;&lt;/html&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_404() As String
            Get
                Return ResourceManager.GetString("Error_404", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot;User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0&quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property ffmpeg_user_agend() As String
            Get
                Return ResourceManager.GetString("ffmpeg_user_agend", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die src=&quot;/player/ ähnelt.
        '''</summary>
        Friend ReadOnly Property Funimation_Player_ID() As String
            Get
                Return ResourceManager.GetString("Funimation_Player_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die src=&quot;https://www.funimation.com/player/ ähnelt.
        '''</summary>
        Friend ReadOnly Property Funimation_Player_ID_2() As String
            Get
                Return ResourceManager.GetString("Funimation_Player_ID_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;a class=&quot;trackVideo ng-binding&quot; href=&quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property Funimation_Split_1() As String
            Get
                Return ResourceManager.GetString("Funimation_Split_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot;&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property Funimation_Split_2() As String
            Get
                Return ResourceManager.GetString("Funimation_Split_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot;src&quot;: ähnelt.
        '''</summary>
        Friend ReadOnly Property Funimation_src_string() As String
            Get
                Return ResourceManager.GetString("Funimation_src_string", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die {&quot;src&quot;: &quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property Funimation_subs_src() As String
            Get
                Return ResourceManager.GetString("Funimation_subs_src", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot;, &quot;kind&quot;: &quot;subtitle&quot;, &quot;type&quot;: &quot;CC&quot;, &quot;language&quot;: &quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property Funimation_Subtitle_String() As String
            Get
                Return ResourceManager.GetString("Funimation_Subtitle_String", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot;, &quot;kind&quot;: &quot;subtitle&quot;, &quot;type&quot;: &quot;Full&quot;, &quot;language&quot;: &quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property Funimation_Subtitle_String2() As String
            Get
                Return ResourceManager.GetString("Funimation_Subtitle_String2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot;, &quot;kind&quot;: &quot;subtitle&quot;, &quot;type&quot;: &quot;full&quot;, &quot;language&quot;: &quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property Funimation_Subtitle_String3() As String
            Get
                Return ResourceManager.GetString("Funimation_Subtitle_String3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;meta property=&quot;og:image&quot; content=&quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property Funimation_thumbnail() As String
            Get
                Return ResourceManager.GetString("Funimation_thumbnail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot;,&quot;resolution&quot;:&quot;adaptive&quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property hls_endString() As String
            Get
                Return ResourceManager.GetString("hls_endString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot;format&quot;:&quot;adaptive_hls&quot;, ähnelt.
        '''</summary>
        Friend ReadOnly Property hls_Value() As String
            Get
                Return ResourceManager.GetString("hls_Value", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;script&gt;
        '''
        '''setInterval(function loadXMLDoc() {
        '''  var xhttp = new XMLHttpRequest();
        '''  xhttp.onreadystatechange = function() {
        '''    if (this.readyState == 4 &amp;&amp; this.status == 200) {
        '''      document.getElementById(&quot;bodypage&quot;).innerHTML = this.responseText;
        '''	  //console.log(this.responseText);
        '''    }
        '''  };
        '''  xhttp.open(&quot;GET&quot;, &quot;/&quot;, true);
        '''  xhttp.send();
        '''}, 1000);
        '''&lt;/script&gt;
        '''&lt;/body&gt;&lt;/html&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property htmlEnd() As String
            Get
                Return ResourceManager.GetString("htmlEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;/a&gt;
        '''
        '''&lt;/div&gt;
        '''
        '''&lt;/div&gt;
        '''
        '''&lt;/div&gt;
        '''
        '''&lt;img alt=&quot;image error&quot; src=&quot;balken1.png&quot; class=&quot;class-balken&quot;&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property htmlnachHardSubs() As String
            Get
                Return ResourceManager.GetString("htmlnachHardSubs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot; class=&quot;imagestyle&quot;&gt;
        '''
        '''&lt;div&gt;
        '''
        '''&lt;span class=&quot;titel&quot; dir=&quot;auto&quot;&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property htmlnachTumbnail() As String
            Get
                Return ResourceManager.GetString("htmlnachTumbnail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;a class=&quot;main_titel&quot;&gt;Placeholder&lt;/a&gt;
        '''&lt;img alt=&quot;image error&quot; src=&quot;balken.png&quot; class=&quot;class-balken&quot;&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property htmlTitlel() As String
            Get
                Return ResourceManager.GetString("htmlTitlel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        '''&lt;head&gt;
        '''&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;/&gt;
        '''&lt;/head&gt;
        '''&lt;html&gt;
        '''       &lt;title&gt;CRD&lt;/title&gt;
        '''              
        '''  &lt;style&gt;
        '''	.main-bg {margin:0 0 0 0;background-color:#F2F2F2;font-family:Consolas;font-size:16px;}
        '''	.div-spacer{width:16px;height:110px;display:block;margin-bottom:14px;position:relative}
        '''	.div-episode{width:730px;height:110px;display:block;margin-bottom:14px;position:relative}
        '''	.class-balken{width:735px;height:8px;display:block;margin-bottom:4px;marg [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property htmlTop() As String
            Get
                Return ResourceManager.GetString("htmlTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;/span&gt;
        '''
        '''&lt;div class=&quot;progressbar&quot;&gt;
        '''
        '''&lt;div class=&quot;progressbar-value&quot; style=&quot;width: 0%&quot;&gt;&lt;/div&gt;
        '''
        '''&lt;/div&gt;
        '''&lt;span  dir=&quot;auto&quot; class=&apos;percenttext&apos;&gt;0%&lt;/span&gt;
        '''&lt;div&gt;
        '''&lt;br&gt;
        '''&lt;span dir=&quot;auto&quot; class=&quot;resotext&quot;&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property htmlvorAufloesung() As String
            Get
                Return ResourceManager.GetString("htmlvorAufloesung", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot;&gt; &lt;img alt=&quot;image error&quot; src=&quot;cc1.png&quot; class=&quot;class-cc&quot;&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property htmlvorHardSubs() As String
            Get
                Return ResourceManager.GetString("htmlvorHardSubs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;/span&gt;
        '''
        '''&lt;a href=&quot;#&quot; class=&quot;cc-wert&quot; title=&quot;Softsubs: ähnelt.
        '''</summary>
        Friend ReadOnly Property htmlvorSoftSubs() As String
            Get
                Return ResourceManager.GetString("htmlvorSoftSubs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die 
        '''		&lt;div class=&quot;div-episode&quot;&gt;
        '''
        '''&lt;img alt=&quot;image error&quot; src=&quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property htmlvorThumbnail() As String
            Get
                Return ResourceManager.GetString("htmlvorThumbnail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot;error&quot;:false,&quot;code&quot;:&quot;ok&quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property LoginSuccess() As String
            Get
                Return ResourceManager.GetString("LoginSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_add_invert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_add_invert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_add_invert_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_add_invert_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_browser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_browser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_browser_invert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_browser_invert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_browser_invert_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_browser_invert_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_button_download_deactivate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_button_download_deactivate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_button_download_default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_button_download_default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_button_download_hovert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_button_download_hovert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_close_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_close_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_close_dark_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_close_dark_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_close_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_close_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_del() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_del", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_mini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_mini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_mini_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_mini_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_mini_dark_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_mini_dark_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_mini_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_mini_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_pause_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_pause_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_pause_play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_pause_play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_pause_play_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_pause_play_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_setting_invert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_setting_invert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_setting_invert_dark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_setting_invert_dark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property main_settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main_settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Main_top() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Main_top", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;/p&gt;
        '''      &lt;/div&gt;
        '''    &lt;/body&gt;
        '''&lt;/html&gt; ähnelt.
        '''</summary>
        Friend ReadOnly Property Post_error_Bottom() As String
            Get
                Return ResourceManager.GetString("Post_error_Bottom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;html&gt;
        '''  &lt;head&gt;
        '''    &lt;meta charset=&quot;UTF-8&quot;&gt;
        '''  &lt;/head&gt;
        '''    &lt;style&gt;
        '''      body {
        '''        text-align: center;
        '''        padding: 40px 0;
        '''        background: #EBF0F5;
        '''      }
        '''        h1 {
        '''          color: #ad3f26;
        '''          font-family: sans-serif;
        '''          font-weight: 900;
        '''          font-size: 40px;
        '''          margin-bottom: 10px;
        '''        }
        '''        p {
        '''          color: #404F5E;
        '''          font-family: sans-serif;
        '''          font-size:20px;
        '''          margin: 0;
        '''        }
        '''      i {
        '''        co [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property Post_error_Top() As String
            Get
                Return ResourceManager.GetString("Post_error_Top", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''       &lt;title&gt;CRD&lt;/title&gt;
        '''              
        '''  &lt;style&gt;
        '''	.main-bg {margin:0 0 0 -36px;background-color:#757575;}
        '''	.imagestyle{width:156px;height:88px;display:block;margin-bottom:4px}	.ulStyle{margin:0 0 0 -10px;display:block;position:relative;margin-top:8px}
        '''	.ulStyle li{margin-left:12px;float:left;display:block;position:relative}
        '''	.listyle{width:156px;display:block;background:#fff;padding:16px;margin-bottom:14px;position:relative;background-color:#b5b3b3}
        '''	.progressbar{height:14p [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property Startuphtml() As String
            Get
                Return ResourceManager.GetString("Startuphtml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &quot;thumbnail&quot;:{&quot;url&quot;:&quot; ähnelt.
        '''</summary>
        Friend ReadOnly Property thumbnailString() As String
            Get
                Return ResourceManager.GetString("thumbnailString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die US cookies can&apos;t be used as long you are logged in.
        '''I delete the curremt session with the unlock, if you want to be logged in with the US cookie you need to enter you data on the left. ähnelt.
        '''</summary>
        Friend ReadOnly Property US_ToolTip() As String
            Get
                Return ResourceManager.GetString("US_ToolTip", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
